# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]


jobs:
  build:

    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Debug --no-restore      
      
    - name: Test
      run: dotnet test  -c Debug --no-build --verbosity normal --settings .runsettings --filter FullyQualifiedName!~IntegrationTests

    - name: Start containers
      run: docker-compose -p kfk -f "tests/docker-compose.yml" up -d
    - name: Integration
      run: dotnet test -c Debug --no-build --verbosity normal --settings .runsettings --filter FullyQualifiedName~IntegrationTests /p:ParallelizeTestCollections=false
    - name: Stop containers
      if: always()
      run: docker-compose -p kfk -f "tests/docker-compose.yml" down

    - name: Report
      run: |
        dotnet tool restore
        dotnet reportgenerator -reports:./artifacts/cob/*/coverage.cobertura.xml -targetdir:artifacts/html -reporttypes:HtmlInline
        dotnet reportgenerator -reports:./artifacts/cob/*/coverage.cobertura.xml -targetdir:artifacts -reporttypes:"Cobertura;HtmlSummary;TextSummary"    

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "artifacts/junit/*.xml"
        output: test-summary.md
      if: always()

    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: artifacts/Cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '35 75'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
